language: python
python:
  - "2.6"
  - "2.7"
  - "3.2"
  - "3.3"
  - "3.4"

# command to install dependencies
install:
  - pip install six==1.9.0

# command to run tests
# script: cd tests && nosetests -v -v --exclude-dir=backtrader/plot
script: cd tests && nosetests -v -v
